version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "danielvdspoel"
    assignees:
      - "danielvdspoel"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      # Group Vue.js related updates
      vue-ecosystem:
        patterns:
          - "vue*"
          - "@vue/*"
          - "@vitejs/*"
          - "vite*"
      # Group development dependencies
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "*config*"
      # Group Tailwind CSS updates
      styling:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "danielvdspoel"
    assignees:
      - "danielvdspoel"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "danielvdspoel"
    assignees:
      - "danielvdspoel"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"