apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio
  labels:
    app.kubernetes.io/name: portfolio
    app.kubernetes.io/component: ingress
  annotations:
    # Traefik-specific annotations
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: portfolio-headers@kubernetescrd
    # Optional: redirect HTTP to HTTPS
    traefik.ingress.kubernetes.io/redirect-scheme: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  tls:
  - hosts:
    - danielvdspoel.com
    - www.danielvdspoel.com
    - www.danielvdspoel.nl
    - danielvdspoel.nl
    secretName: portfolio-tls
  rules:
  - host: danielvdspoel.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-service
            port:
              number: 80
  - host: www.danielvdspoel.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-service
            port:
              number: 80
  - host: www.danielvdspoel.nl
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: portfolio-service
              port:
                number: 80
  - host: danielvdspoel.nl
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: portfolio-service
              port:
                number: 80
